import type { Metadata } from "next";
import { Geist_Mono, Fleur_De_Leah, Thasadith } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fleurDeLeah = Fleur_De_Leah({
  variable: "--font-fleurDeLeah",
  weight: ["400"],
  subsets: ["latin"],
});

const thasadith = Thasadith({
  variable: "--font-thasadith",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistMono.variable,
        fleurDeLeah.variable,
        thasadith.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col sm:w-md sm:min-h-[90dvh] sm:my-[5dvh] sm:m-auto sm:border-foreground sm:border-4 sm:border-double sm:rounded-2xl sm:shadow-lg">
        {children}
      </body>
    </html>
  );
}
